[phases.setup]
nixPkgs = ['python312', 'python312Packages.pip', 'nodejs']

[phases.install]
cmds = ['pip install -r requirements.txt']

[start]
cmd = "streamlit run dashboard.py --server.port $PORT --server.headless true"
