
[phases.setup]
nixPkgs = ['python312']

[phases.install]
cmds = ['python -m venv /opt/venv', '. /opt/venv/bin/activate', 'pip install --break-system-packages -r requirements.txt']

[start]
cmd = "streamlit run dashboard.py --server.port $PORT --server.headless true"
